version: "0.0.7"

# Enables debug mode
debug: false

# Should loot drop from passive animals?
neutral-mobs-drop: false

# Should loot drop from mobs from spawners?
spawner-mobs-drop: false

# Controls item names floating above dropped loot.
# Disable if you have another plugin for this.
show-item-nameplates: true

# If set to true, tomes drop, and you must use them to
# enchant. Otherwise, it uses vanilla.
custom-enchanting: true

# Should tome enchantments stack? If true, tomes will
# add to current enchantments. If false, tomes will
# only work on items if the tome has a more powerful
# enchantment.
enchantments-stack: true

# Chance that items will have any random upgrade
# value applied on drop.
random-upgrade-quantityBonus: 0.1

# Chance that items will have additional random upgrades
# applied to the drop. This stacks, so 0.1 would
# be 10% quantityBonus of +2, 1% quantityBonus of +3, 0.1% quantityBonus
# of +4, etc.
multi-upgrade-quantityBonus: 0.1

# Chance that items will have a bonus to their
# quality, increasing its base stat
random-quality-quantityBonus: 0.1

# Chance that items will have additional random quality
# ups applied to the drop. This stacks, so 0.1 would
# be 10% quantityBonus of Superior, 1% quantityBonus of Perfect, 0.1%
# quantityBonus of Ultimate, etc.
multi-quality-quantityBonus: 0.1

# How long loot drops assigned to a specific player
# should disallow anyone else to pick it up. The
# assigned player is determiend randomly from the
# list of attackers, with weight based on dmg dealt
loot-protect-time: 10

# Worlds where loot items wlll drop
enabled-worlds:
- main
- yololand

# Settings if you have the Faceland plugin, Beast
beast:
  beast-mode-activate: false
  range-before-penalty: 15

# Probability that mobs will drop an item of each
# type when it is killed
drops:
  normal-drop: 0.2
  socket-gem: 0.4
  enchant-gem: 0.1
  upgrade-scroll: 0.1
  reveal-powder: 0.1
  identity-tome: 0.01
  junk-item: 0.1
  unique-item: 0.1
  socket-extender: 0.000001
  unidentified-item: 0.1

# Items that cannot be altered by upgrade scrolls
cannot-be-upgraded:
- Fuck
- This
- Shit