name: Loot
version: ${project.version}
main: info.faceland.loot.LootPlugin
depend:
  - Facecore
softdepend:
  - Strife

commands:
  loot:
    aliases: [l]

permissions:
  loot.command.spawn:
    default: op
  loot.command.give:
    default: op
  loot.command.simulate:
    default: op
  loot.command.chest:
    default: op