name: Loot
version: ${project.version}
main: info.faceland.loot.LootPlugin
api-version: 1.15
depend:
  - Facecore
softdepend:
  - Strife
  - Vault
  - PlayerPoints
  - InteractiveChatDiscordSrvAddon

commands:
  loot:
    aliases: [l]

permissions:
  loot.command.spawn:
    default: op
  loot.command.give:
    default: op
  loot.command.simulate:
    default: op