name: ${project.build.name}
version: ${project.build.version}
main: info.faceland.loot.LootPlugin
depend: [Facecore, ProtocolLib]

commands:
  loot:
    aliases: [l]

permissions:
  loot.command.spawn:
    default: op
  loot.command.give:
    default: op
  loot.command.simulate:
    default: op